spring.application.name=Spring_MVC_Employee
# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/Spring_MVC_Employee?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#================================
#JPA /HIBERNATE
#=================================
spring.mvc.view.prefix=
spring.mvc.view.suffix=.jsp
